### PR TITLE
Added `__clone()` to `AbstractEntity`

### PR DESCRIPTION
**Pull request by wnowicki**
### Added
- `AbstractEntity` clone handling for object properties

### CODE REVIEW

**Comment by EvanBarbour3** [comment]
@wnowicki 👍

**Comment by wnowicki** [comment]
@EvanBarbour3 please do proper approval

**Comment by 00eadeyemi** [comment]
👍  Tests are good

**Comment by EvanBarbour3** [comment]
@wnowicki How do you know that was my approval? 😉

**Pull request merged**
