### PR TITLE
Repository

### PR DESCRIPTION
**Pull request by wnowicki**
## Features
- New concepts:
    - `Indexable`
    - `Persistable`
- Repository concepts
    - `ReadRepository`
    - `Repository`
    - `WriteRepository`

### CODE REVIEW

**Comment by wnowicki** [comment]
1. `IndexableEntity` maybe it should be something like `uid()` (baseline) instead of *getter style* method?
2. `ReadRepository` and `WriteRepository` need to rethink method names.
3. `RecordableAbstractEntity` will be delivered depending on 1. 2. decisions.

**Comment by srleach** [comment]
1. `IndexableEntity` - I'd probably go with the first (baseline style) as if we're using get**** we may have a collision with a field name (for example getIndex would be good choice, but then we can't have field named index) - so `uid()` or `uniqueId()` etc would be my choice.
2. Don't think there's an issue with naming - if you really don't like you could go with `PersistRepo...` or `PersistenceRepo...` and `RetrievalRepo...`
3. `RecordableEntity` - I'd _maybe_ consider renaming to `PersistableEntity`

```php
class Loan extends AbstractEntity implements PersistableEntity {

}
```

**Comment by srleach** [comment]
@wnowicki

**Comment by srleach** [comment]
On point 3. - i'd also maybe consider just `Persistable` 

```php
class Loan extends AbstractEntity implements Persistable {

}
```

**Comment by 00eadeyemi** [comment]
1. If there is a possibility that using a getter will may cause a collision as pointed by Sean then don't use it otherwise the current implementation is alright .  
2. As long as the class name is a reasonable noun the naming shouldn't matter though ReadRepository and WriteRepository do sound like verbs.

**Comment by EvanBarbour3** [comment]
Not much I can think so say, other than I prefer `getId()` to `uid()`.

**Comment by wnowicki** [comment]
1. happy with `uid()` but we need as well something on `IndexableEntity` to set index so:
    - `uid($id = null)` for getting and setting
    - or `getId()` and `setId($id)` 
2. So stick to the current names
3. Happy to change the name for one that team will agree

**Comment by wnowicki** [comment]
@srleach @EvanBarbour3

**Comment by srleach** [comment]
1: I'm mostly concerned about collisions with legitimate fields on the entity when using the setField and getField pattern for the ID. By the above suggestions, I'd go with providing a function `uid()` on the entity as follows:
(pseudocode)
```php
protected $uidField = 'id';

public function uid($id - null){
    
    if (is_null($id)) {
        return     $this->{'get' . NameHelper:lowerToSnake($this->uidField)}();
    }
    
    return $this->{'set' . NameHelper:lowerToSnake($this->uidField)}($id);
}

This means to set it as indexable, we need to set the property `protected $uidField = 'id';`

2: :+1

3: My suggestion is PersistableEntity

**Comment by srleach** [comment]
Adjective
persistable ‎(not comparable)

(computing) That can be made to persist; permanent. 

😹

**Comment by wnowicki** [comment]
@srleach

**Pull request merged**
