### PR TITLE
Add check for interface

### PR DESCRIPTION
**Pull request by srleach**
## Features
- Added *interface* support to `AbstractEntity`

### CODE REVIEW

**Comment by srleach** [comment]
@wnowicki I found a bug 👎 
@wnowicki I fixed the bug 👍

**Comment by wnowicki** [comment]
- where do you want to find the bug ?
- I think you changed behaviour of something which we need to discuss first
- now `private function classExists($class)` is not a descriptive name for this method

**Comment by srleach** [comment]
- not sure what you mean
- behaviour has changed, but in line with what I would expect (and you
would too, since you wrote the code expecting interface ;) ) for our use.
- name I agree with, maybe just 'instantiable()' or something?

On Thursday, 16 June 2016, Wojtek <notifications@github.com> wrote:

>
>    - where do you want to find the bug ?
>    - I think you changed behaviour of something which we need to discuss
>    first
>    - now private function classExists($class) is not a descriptive name
>    for this method
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PayBreak/foundation/pull/10#issuecomment-226586877>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AM6gFVw0hAqYb9-KxSLxtZOjQgFCaqRYks5qMaJugaJpZM4I3o9y>
> .
>


-- 

Sean Leach

Software Developer
Phone: 033 33 444 224
Email: sean.leach@paybreak.com

-- 
 

afforditNOW <http://www.afforditnow.com> is a suite of finance products 
offered by PayBreak Limited, a registered company in England with 
registration number  07445012 and registered offices at Grosvenor House, 20 
Barrington Road, Altrincham, WA14 1HB.
------------------------------

This e-mail, together with any files transmitted with it, are confidential, 
and are intended solely for the use of the individual or entity to whom 
they are addressed. Any unauthorised dissemination or copying of this 
e-mail or its attachments, and any use or disclosure of any information 
contained in them, is strictly prohibited, and may also be illegal. If you 
have received this e-mail in error please notify hello@paybreak.com and 
delete it from your system.

**Comment by srleach** [comment]
@wnowicki I've added tests for this, and made names a little more descriptive. what are your thoughts?

**Pull request merged**
